blogs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^titles/$', views.titles, name='titles'),
    url(r'^titles/(?P<title_id>\d+)/$', views.title, name='title'),
    url(r'^new_blog/$', views.new_blog, name='new_blog'),
    url(r'^titles/(?P<title_id>\d+)/edit_blog/$', views.edit_blog, name='edit_blog'),
    url(r'^titles/(?P<title_id>\d+)/reply/$', views.reply, name='reply'),
]

myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('blogs.urls', namespace='blogs')),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class MyBlog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)
    def __str__(self):
        return self.title

class Reply(models.Model):
    topic = models.ForeignKey(MyBlog)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)
    def __str__(self):
        return self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from blogs.models import MyBlog, Reply

class MyBlogForm(forms.ModelForm):
    class Meta:
        model = MyBlog
        fields = ('title', 'content')

class PostForm(forms.ModelForm):
    class Meta:
        model = MyBlog
        fields = ('title', 'content')

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['text']

blogs/views.py
from django.shortcuts import render
from .models import MyBlog, Reply
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from blogs.forms import MyBlogForm, PostForm, ReplyForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    articles = MyBlog.objects.all().order_by('-add_time')[:4]
    context = {'articles': articles}
    return render(request, 'blog/index.html', context)

@login_required
def titles(request ):
    #titles = MyBlog.objects.order_by('add_time')
    titles = MyBlog.objects.filter(owner=request.user).order_by('add_time')
    #reply = Reply.objects.all()

    context = {'titles': titles}
    return render(request, 'blog/titles.html',context)

@login_required
def title(request, title_id):
    title = MyBlog.objects.get(id=title_id)
    replys = title.reply_set.all()


    context = {'title': title, 'replys':replys}
    return render(request, 'blog/title.html', context)

@login_required
def new_blog(request):
    if request.method != 'POST':
        form = MyBlogForm()
    else:
        form = MyBlogForm(request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return HttpResponseRedirect(reverse('blogs:titles'))
    context = {'form': form}
    return render(request, 'blog/new_blog.html', context)

@login_required
def edit_blog(request, title_id):
    blog = MyBlog.objects.get(id=title_id)
    title = blog.title
    if blog.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = PostForm(instance=blog)
    else:
        form = MyBlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("blogs:title", args=[blog.id]))
    context = {'blog': blog, 'form': form, 'title': title}
    return render(request, 'blog/edit_blog.html', context)

def reply(request, title_id):
    blog = MyBlog.objects.get(id=title_id)
    if request.method != 'POST':
        replyform = ReplyForm()
    else:
        replyform = ReplyForm(data=request.POST)
        if replyform.is_valid():
            add_reply = replyform.save(commit=False)
            add_reply.topic = blog
            add_reply.owner = request.user
            add_reply.save()
            return HttpResponseRedirect(reverse('blogs:title', args=[blog.id]))
    context = {'blog': blog, 'replyform': replyform}
    return render(request, 'blog/reply.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form}
    return render(request, 'user/register.html', context)

blogs/templates/blog/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-U-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, inital-scale=1">
    <title>我的博客</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!-- Static navbar-->
<nav class="navbar navbar-default navbar-static-top">
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'blogs:index' %}">
            博客
        </a>
    </div>

    <div id="navbar" class="navbar-collapse collaose">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'blogs:titles' %}">标题</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a>你好，{{ user.username }}</a></li>
                <li><a href="{% url 'users:logout' %}">注销</a></li>
            {% else %}
                <li><a href="{% url 'users:register' %}">注册</a></li>
                <li><a href="{% url 'users:login' %}">登录</a></li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div>
</body>
</html>

blogs/templates/blog/edit_blog.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>修改文章</h2>
{% endblock header %}
{% block content %}
    <p>修改文章</p>
    <form action="{% url "blogs:edit_blog" blog.id %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
    <button name="submit" class="btn btn-primary">提交</button>
    {% endbuttons %}
    </form>

{% endblock content %}

blogs/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <div class="jumbotron">
    <h1>博客主页</h1>
    </div>
{% endblock header %}

{% block content %}
    <style type="text/css">
  .test_demo_clip{text-overflow:clip; overflow:hidden; white-space:nowrap; width:200px;}
  .test_demo_ellipsis{text-overflow:ellipsis; overflow:hidden;  width:1000px;height:138px;}
</style>
    {% if user.is_authenticated %}:
    <h2><a href="{% url 'blogs:new_blog' %}">点此</a>开始编写你的博客</h2>
    {% else %}
        <h2>
    <a href="{% url 'users:register' %}">注册一个账号</a>来编写属于你自己的博客，
    并且向别人展示你的兴趣。
    </h2>
    {% endif %}
        <div>
        {% for article in articles %}
            <div >
                <div class="panel panel-success">
                    <div class="panel-heading">{{ article.title }}</div>
                        <div class="panel-body test_demo_ellipsis">
                            <a href="{% url 'blogs:title' article.id %}">{{ article.content }}</a>
                        </div>
                    </div>
                </div>
        {% empty %}
            无内容。
        {% endfor %}
</div>

{% endblock content %}

blogs/templates/blog/new_blog.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>发布新文章</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'blogs:new_blog' %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-primary">新文章</button>
    {% endbuttons %}
    </form>
{% endblock content %}

blogs/templates/blog/reply.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h3>回复</h3>
{% endblock header %}

{% block content %}
    <form action="{% url 'blogs:reply' blog.id %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form replyform %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">回复</button>
    {% endbuttons %}
    </form>
{% endblock content %}

blogs/templates/blog/title.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>{{ title }}
    <small>作者:{{ title.owner }}</small></h2>
{% endblock header %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
        <h3>{{ title.add_time|date:'Y-m-d H:i:s ' }}
        <small>
            <a href="{% url 'blogs:edit_blog' title.id %}">修改文章</a>
        </small>
        </h3>
        </div>
        <div class="panel-body">
        {{ title.content|linebreaks }}
        </div>
    </div>
    <div class="panel panel-success">
        <div class="panel-heading">
            <h4>评论
            <small>
                <a href="{% url 'blogs:reply' title.id %}">发表评论</a>
            </small>
            </h4>
        </div>
        <div class="panel-body">
        {% for reply in replys %}
                <ul>
                <li>{{ reply.date_added|date:'Y-m-d-H:i:s' }} --  {{ reply.owner }}<br/>
                    {{ reply.text }} </li>
                </ul>
            {% empty %}
                <p>暂无评论</p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

blogs/templates/blog/titles.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>标题</h2>
{% endblock header %}

{% block content %}
    <ul>
    {% for title in titles %}
        <li>
        <a href="{% url 'blogs:title' title.id %}">{{ title }}</a>
        </li>
    {% empty %}
        <p>无任何内容...</p>
    {% endfor %}
    </ul>
    <h4><a href="{% url 'blogs:new_blog' %}">添加新文章</a></h4>
{% endblock content %}

users/templates/user/login.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>账号登录</h2>
{% endblock header %}

{% block content %}
    <form method="POST" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-primary">登录</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
    </form>
{% endblock content %}

users/templates/user/register.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h3>账号注册</h3>
{% endblock header %}
{% block content %}
    <form action="{% url 'users:register' %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
    <button name="submit" class="btn btn-primary">注册</button>
        {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
    </form>
{% endblock content %}